data:
  classes:
    - car
    - house
    - road
    - swimming pool
    - tree
    - yard
  image_size: 640  
  batch_size: 8
  num_workers: 4
  train_path: "Training Datasets/train"
  val_path: "Training Datasets/valid"

model:
  backbone: "resnet18"
  pretrained: true
  confidence_threshold: 0.5
  nms_threshold: 0.4

training:
  epochs: 3
  learning_rate: 0.001
  weight_decay: 0.0005
  save_dir: "checkpoints"

api:
  host: "0.0.0.0"
  port: 8000
